spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://qianlihui.com:3306/account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    encoding: UTF-8
